let catalogoNombres = [
    {
        id:101,
        idNombreCatalogo: "Desierto",
    },
    {
        id:102,
        idNombreCatalogo: "Montaña",
    },
    {
        id:103,
        idNombreCatalogo: "Playa",
    },
    {
        id:104,
        idNombreCatalogo: "Selva",
    },
    {
        id:105,
        idNombreCatalogo: "Valle",
    },
]
let catalogoCategoria = [
    {
        id:101,
        nombreCategoria:"Desierto",
        idImagenPrincipal: 1,
        ImagenPrincipal: "../img/desierto/desierto_inicio.jpg",
        idTituloCatalogo: 11,
        TituloCatalogo: "DESTINOS: DESIERTO",
    },
    {
        id:102,
        nombreCategoria: "Montaña",
        idImagenPrincipal: 2,
        ImagenPrincipal: "../img/montaña/montaña_inicio.jpg",
        idTituloCatalogo: 12,
        TituloCatalogo: "DESTINOS: MONTAÑA",
    },
    {
        id:103,
        nombreCategoria: "Playa",
        idImagenPrincipal: 3,
        ImagenPrincipal: "../img/playa/playa_inicio.jpg",
        idTituloCatalogo: 13,
        TituloCatalogo: "DESTINOS: PLAYA",
    },
    {
        id:104,
        nombreCategoria: "Selva",
        idImagenPrincipal: 4,
        ImagenPrincipal: "../img/selva/selva_inicio.jpg",
        idTituloCatalogo: 14,
        TituloCatalogo: "DESTINOS: SELVA",
    },
    {
        id:105,
        nombreCategoria: "Valle",
        idImagenPrincipal: 5,
        ImagenPrincipal: "../img/valle/valle_inicio.jpg",
        idTituloCatalogo: 15,
        TituloCatalogo: "DESTINOS: VALLE",
    },
];

/*let cardTours = [
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
    {
        idCategoria: ,
        nombreCategoria: ,
        idCard: ,
        nombreLugarCard: ,
        idPrecio: ,
        precio: ,
    },
]*/